### ISSUE TITLE
Incompatibility with current versions of CheckMK

### ISSUE THREAD

**Issue by Jay2k1** [Notausstieg0309/checkmk-plugin-access-logs#6]
When updating CheckMK, this happens:

```
-| Verifying Checkmk configuration...
-|  01/04 Rulesets...
-| Failed to load plugin /omd/sites/monitoring/local/share/check_mk/web/plugins/wato/access_logs.py: name 'Tuple' is not defined
-| Traceback (most recent call last):
-|   File "/omd/sites/monitoring/lib/python3/cmk/gui/utils/__init__.py", line 66, in load_web_plugins
-|     exec(f.read(), globalvars)
-|   File "<string>", line 8, in <module>
-| NameError: name 'Tuple' is not defined
-| Failed to load plugin /omd/sites/monitoring/local/share/check_mk/web/plugins/wato/access_logs.py: name 'RegExp' is not defined
-| Traceback (most recent call last):
-|   File "/omd/sites/monitoring/lib/python3/cmk/gui/utils/__init__.py", line 66, in load_web_plugins
-|     exec(f.read(), globalvars)
-|   File "<string>", line 69, in <module>
-| NameError: name 'RegExp' is not defined
-|  02/04 UI extensions...
-| Failed to load plugin /omd/sites/monitoring/local/share/check_mk/web/plugins/wato/access_logs.py: name 'RegExp' is not defined
-| Traceback (most recent call last):
-|   File "/omd/sites/monitoring/lib/python3/cmk/gui/utils/__init__.py", line 66, in load_web_plugins
-|     exec(f.read(), globalvars)
-|   File "<string>", line 69, in <module>
-| NameError: name 'RegExp' is not defined
-| Incompatible file 'access_logs' of extension package 'access_logs 1.2'
-| Error: name 'RegExp' is not defined
-|
-| You can abort the update process (A) or disable the extension package (d) and continue the update process.
-| Abort the update process? [A/d]
```

I can then press `d` to disable the plugin, wait for the installation to finish, and then run `mkp enable access_logs` which then flawlessly re-enables it. This happens on every CMK update.

**Comment by dnlldl** [comment]
Doesn't work anymore as of 2.3, developer isn't responding either.

**Comment by 47k** [comment]
Same with CheckMK 2.2.0
